### ISSUE TITLE
False cache hit when testing Phobos modules

### ISSUE THREAD

**Issue by CyberShadow** [dragon-lang/rund#20]
Steps to reproduce:

1. `chdir` to a Phobos checkout (`.../phobos/std`)
2. Run `rund -g -debug -unittest -main stdio.d`
3. Edit `stdio.d` (e.g. add some garbage)
4. Run `rund -g -debug -unittest -main stdio.d`

rund seems to use the previous execution result even though the file on disk has been edited.

I'm guessing it doesn't even check the `stdio.d` timestamp because it is a Phobos module. However, the compiler will always read and compile source files on its command line, so rund should exempt them from that rule. This will also make it on par with rdmd.

**Comment by marler8997** [comment]
Fix here: https://github.com/dragon-lang/rund/pull/21

**Comment by CyberShadow** [comment]
Thank you Jonathan, I just ran into this on another machine yesterday and confirmed the fix worked by updating rund.

**Comment by marler8997** [comment]
Good to hear. Hope all is well.
